language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

env:
    - DJANGO=1.9.8
    - DJANGO=1.9.7
    - DJANGO=1.8.14
    - DJANGO=1.8.13
    - DJANGO=1.7.11
    - DJANGO=1.7.10
    - DJANGO=1.6.11
    - DJANGO=1.6.10

matrix:
    exclude:
        - python: "2.6"
          env: DJANGO=1.9.8
        - python: "2.6"
          env: DJANGO=1.9.7
        - python: "2.6"
          env: DJANGO=1.8.14
        - python: "2.6"
          env: DJANGO=1.8.13
        - python: "2.6"
          env: DJANGO=1.7.11
        - python: "2.6"
          env: DJANGO=1.7.10

install:
    - pip install Django==$DJANGO
    - pip install -e .

script:
    - python run_tests.py

notifications:
    email:
        recipients:
          - jon@faustman.org
        on_success: never
        on_failure: always
